//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gr01MonsterUniversity.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class monster_universityEntities : DbContext
    {
        public monster_universityEntities()
            : base("name=monster_universityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PEEEMP_EMPLE> PEEEMP_EMPLE { get; set; }
        public virtual DbSet<PEESC_ESTCIV> PEESC_ESTCIV { get; set; }
        public virtual DbSet<PESEX_SEXO> PESEX_SEXO { get; set; }
        public virtual DbSet<XEOPC_OPCIO> XEOPC_OPCIO { get; set; }
        public virtual DbSet<XEPER_PERFI> XEPER_PERFI { get; set; }
        public virtual DbSet<XEUSU_USUAR> XEUSU_USUAR { get; set; }
        public virtual DbSet<XEUXP_USUPE> XEUXP_USUPE { get; set; }
        public virtual DbSet<XEOXP_OPCPE> XEOXP_OPCPE { get; set; }
    }
}
