//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gr01MonsterUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEEEMP_EMPLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEEEMP_EMPLE()
        {
            this.XEUSU_USUAR = new HashSet<XEUSU_USUAR>();
        }
    
        public string PEEEMP_CODIGO { get; set; }
        public string PEEEMP_CEDULA { get; set; }
        public string PEEEMP_NOMBRES { get; set; }
        public string PEEEMP_APELLIDOS { get; set; }
        public string PEEEMP_EMAIL { get; set; }
        public Nullable<System.DateTime> PEEEMP_FECHANAC { get; set; }
        public string PEEEMP_DIRECCION { get; set; }
        public string PEEEMP_TELEFONO { get; set; }
        public string PEEEMP_CELULAR { get; set; }
        public Nullable<int> PEEEMP_HIJOS { get; set; }
        public string PEPSEX_CODIGO { get; set; }
        public string PEESC_CODIGO { get; set; }
        public string PEEMP_FOTO { get; set; }
    
        public virtual PEESC_ESTCIV PEESC_ESTCIV { get; set; }
        public virtual PESEX_SEXO PESEX_SEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XEUSU_USUAR> XEUSU_USUAR { get; set; }
    }
}
