//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gr01MonsterUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESEX_SEXO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PESEX_SEXO()
        {
            this.PEEEMP_EMPLE = new HashSet<PEEEMP_EMPLE>();
        }
    
        public string PEPSEX_CODIGO { get; set; }
        public string PEPSEX_DESCRI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEEEMP_EMPLE> PEEEMP_EMPLE { get; set; }
    }
}
