//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gr01MonsterUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XEOPC_OPCIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XEOPC_OPCIO()
        {
            this.XEPER_PERFI = new HashSet<XEPER_PERFI>();
        }
    
        public string XEOPC_CODIGO { get; set; }
        public string XEOPC_DESCRI { get; set; }
        public string XEOPC_URL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XEPER_PERFI> XEPER_PERFI { get; set; }
    }
}
