//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gr01MonsterUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XEPER_PERFI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XEPER_PERFI()
        {
            this.XEUXP_USUPE = new HashSet<XEUXP_USUPE>();
            this.XEOPC_OPCIO = new HashSet<XEOPC_OPCIO>();
        }
    
        public string XEPER_CODIGO { get; set; }
        public string XEPER_DESCRI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XEUXP_USUPE> XEUXP_USUPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XEOPC_OPCIO> XEOPC_OPCIO { get; set; }
    }
}
