//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gr01MonsterUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XEUSU_USUAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XEUSU_USUAR()
        {
            this.XEUXP_USUPE = new HashSet<XEUXP_USUPE>();
        }
    
        public string PEEEMP_CODIGO { get; set; }
        public string XEUSU_PASWD { get; set; }
        public string XEEST_CODIGO { get; set; }
        public string XEUSU_PIEFIR { get; set; }
        public Nullable<System.DateTime> XEUSU_FECCRE { get; set; }
        public Nullable<System.DateTime> XEUSU_FECMOD { get; set; }
        public Nullable<byte> XEUSU_REQ_CAMBIO { get; set; }
    
        public virtual PEEEMP_EMPLE PEEEMP_EMPLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XEUXP_USUPE> XEUXP_USUPE { get; set; }
    }
}
