//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gr01MonsterUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XEUXP_USUPE
    {
        public string PEEEMP_CODIGO { get; set; }
        public string XEUSU_PASWD { get; set; }
        public string XEPER_CODIGO { get; set; }
        public Nullable<System.DateTime> XEUXP_FECASI { get; set; }
    
        public virtual XEPER_PERFI XEPER_PERFI { get; set; }
        public virtual XEUSU_USUAR XEUSU_USUAR { get; set; }
    }
}
